### ISSUE TITLE
User Entity customFields attribute needed

### ISSUE THREAD

**Issue by alinmiron** [timetorock/laravel-rocket-chat#10]
Can you add in the User Model and in the Create User method the customFields attribute?  See the documentation:
https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/users-endpoints/create-user

This is IMHO very useful for customized setups, 
10x.

**Comment by timetorock** [comment]
Hi @alinmiron. Please, check this release: https://github.com/timetorock/laravel-rocket-chat/releases/tag/0.4.4
